name: Deploy Health API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Build da imagem Blue
        run: docker build -t health-api:blue -f Dockerfile .

      - name: Build da imagem Green
        run: docker build -t health-api:green -f Dockerfile .

      - name: Rodar containers (teste local)
        run: |
          docker stop health-api-blue || true
          docker stop health-api-green || true
          docker rm health-api-blue || true
          docker rm health-api-green || true
          docker run -d --name health-api-blue -p 8001:8000 health-api:blue
          docker run -d --name health-api-green -p 8002:8000 health-api:green

      - name: Alternar Nginx (Blue/Green)
        run: |
          chmod +x scripts/switch.sh
          ./scripts/switch.sh
